# the name of the workflow as it will appear in the "Actions" tab of the
# Github repository
name: learn-github-actions

# Optional
run-name: ${{ github.actor }} is learning Github learn-github-actions
# only trigger this workflow when there is a push action to branches: main, dev.

on:
  push:
    branches:
      - main
      - dev
      - staging
  # pull_request
  # - main
  # - dev
  # - staging

# define variables for global scope
env:
  globalVar: "Global variable"
  commonVar: "Global common variable"

# group together all jobs that run in the learn-github-actions workflow.
jobs:
  check-bats-version: # jobs.<job_id>, job_id = check-bats-version
    name: check-bats # jobs.<job_id>.name, name = check-bats
    runs-on: ubuntu-latest # jobs.<job_id>.runs-on
    environment:
      name: dev
      url: http://github.com
    env:
      jobVar: "Job-scoped variable"
      commonVar: "Job common variable"
    steps:
      # step 1
      - name: checkout step
        uses: actions/checkout@v3

      # step 2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      # step 3
      - name: install bats
        run: npm install -g bats && bats -v

      - name: logging
        run: echo "hello github actions from ubuntu, $myName, ${{ env.commonVar }}"

        env:
          myName: ${{ vars.USER }}
          stepVar: "step variable"
          commonVar: "Step common variable"

      # step 4, a step without a name
      - run: echo $PATH
      - name: what is the secret?
        run: echo "my secret is ${{ secrets.MySecret }}"
